### ISSUE TITLE
show() is kind of useless

### ISSUE THREAD

**Issue by mattdesl** [npm-dom/dom-style#6]
Right now show() is the same as `style(el, 'display', 'inline')` which makes it pretty useless if you're using anything other than an inline element.

Looking at jQuery, they seem to cache the previous display value. It's fairly nasty and probably better suited in a separate module... opening up here to see if you guys have any further insight?

https://github.com/jquery/jquery/blob/895ea6887dd02a44067d041db00c355c80e930a3/src/css.js#L153

**Comment by paulirish** [comment]
use the elem.hidden property. 

![image](https://cloud.githubusercontent.com/assets/39191/6097179/e6403cca-afc3-11e4-994d-d970417c4444.png)

(polyfill it in CSS if they need under IE11)


either that or remove it from the library. separation of concerns bites big here.

**Comment by azer** [comment]
yeah we can remove it @mattdesl could u send a PR ?

**Comment by TehShrike** [comment]
@mattdesl removed show/hide in https://github.com/npm-dom/dom-style/commit/42cf05ac2546528b9c4759082b3c1844b3caa217
